### ISSUE TITLE
Subquery and search

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net-core#17]
I want this to be working also for strings. I use ```"list_view": "(SELECT * table LEFT JOIN table2 ...) t``` in config.json very often to get a quick lookups. I don't want to create a dedicated views.

https://github.com/osalabs/osafw-asp.net-core/blob/a6235a3febb38726725057491ffe1972c3037dcd/osafw-app/App_Code/fw/FwController.cs#L455-L460

**Comment by osalabs** [comment]
I see, for the subquery, there is only int search because we can't obtain field type. However, because of using parameters, we might not need types at all... will check

**Comment by osalabs** [comment]
I didn't found a way to pass object as a parameter. I hope SQL server can automatically convert it to the field type, but that's not the case. Therefore this won't work for subqueries as is.
Alternative way would be to define field types in search_fields, but I don't want to complicate these things.
Simpler would be just override `setListSearch()` in controller
