### ISSUE TITLE
sessions for developers doesn't work out of the box

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net-core#32]
So, we have:
`FwConfig.overrideSettingsByName(enviroment, ref settings);`
https://github.com/osalabs/osafw-asp.net-core/blob/master/osafw-app/Startup.cs#L38

`public static void overrideSettingsByName(string override_name, ref Hashtable settings)`
https://github.com/osalabs/osafw-asp.net-core/blob/master/osafw-app/App_Code/fw/FwConfig.cs#L175

This works only if we change `"developer": {` to `"Development" here: {` 
https://github.com/osalabs/osafw-asp.net-core/blob/master/osafw-app/appsettings.json#L82

As I understand we can't access Hostname in the Startup.cs, so it's still not clear how to handle session connection path for several local developers and test(beta) environment.

**Comment by osalabs** [comment]
should work now
