### ISSUE TITLE
Force logout users

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net-core#39]
If some user is logged in and you change its status to Inactive/Deleted or permanently delete that user, the logged user is still active.
It's expected to log out inactive/deleted users immediately.

I didn't find a way to clear a particular user session using .NET Core instruments. I saw several examples of the ".AspNetCore.Session" cookie decryption and obtaining the session ID from the DB storage and then deleting it. But I don't understand how to incorporate that code into the OSAFW. And I'm not sure if it's 100% guaranteed that deleting from the "fwsessions" table immediately clears the user session on the next requests. Probably the session values can be cached somewhere on the application level.

Currently, I implemented this type of force logout via FwCache and FwHooks in one project.

**Comment by osalabs** [comment]
Simplest approach would be to read user and check `status` in FwHooks. If it's not active - do not continue with request and logoff.

**Comment by vladsavchuk** [comment]
> Simplest approach would be to read user and check `status` in FwHooks. If it's not active - do not continue with request and logoff.

I did something like this in one project employing `FWCache ` and watching the status change in the `Users::update`
