### ISSUE TITLE
Entity Builder: Index list sorting

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-asp.net-core#85]
It'd be nice to add consistent sorting for generated index statements. After a minor change in the entities description structure and regenerating `database.sql`, the order of index statements becomes different for all tables with multiple indexes. So I have to review the whole file diff to make sure that nothing else changed.

![image](https://github.com/osalabs/osafw-asp.net-core/assets/35847544/8719e88d-4028-4d69-b77d-62deef10819b)

**Comment by osalabs** [comment]
Done in a branch, will be merged to master soon
